site_name: Digitizing Documentation
nav:
  - Home: index.md
  - User Guide:
    - Preliminary Setup: 
      - Prelim_Setup/index.md
      - dt BC100: dt_BC100/morning.md
      - dt Flat Bed: dt_FlatBed/morning.md
    - Pre-Flight:
      - Pre_Flight/index.md
      - dt BC100: dt_BC100/preflight.md
      - dt Flat Bed: dt_FlatBed/preflight.md
    - Process:
      - Digi_Process/index.md
      - dt BC100: dt_BC100/digiproc.md
      - dt Flat Bed: dt_FlatBed/digiproc.md
    - Export:
      - Export/index.md
      - dt BC100: dt_BC100/export.md
      - dt Flat Bed: dt_FlatBed/export.md
    - Troubleshooting:
      - Troubleshoot/index.md
      #- dt BC100: Troubleshoot/troubleshoot.md
      #- dt Flat Bed: Troubleshoot/troubleshoot.md
  - About:
    - About/index.md
    - Process: About/process.md
    - Glossary: About/glossary.md
    - Admin Setup: About/admin_setup.md
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: green
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: teal
  font:
    # Font for text
    text: Montserrat
    # Font for code
    code: Roboto Mono
  features:
    # Add navigation tabs; not shown on mobile
    #- navigation.tabs
    # Add top-level sections are rendered as groups in the sidebar for viewports above 1220px
    - navigation.sections
    # A breadcrumb navigation is rendered above the title of each page,
    - navigation.path
    - navigation.prune
    - navigation.indexes
    # The sidebar is automatically scrolled so that the active anchor is always visible
    - toc.follow
    #  always render the toc as part of the navigation sidebar on the left
    - toc.integrate
    - search.suggest
    - search.highlight
  plugins:
    - search
    - optimize
    - privacy:
      # Don't use settings locally
      enabled: !ENV [CI, false]
      # Have external links open in a new tab
      links_attr_map:
        target: _blank
  markdown_extensions:
    # Add snippets with the format
    - pymdownx.snippets:
        auto_append:
          - includes/abbreviations.md
  watch:
    - includes
  highlightjs: true
  hljs_style: github
  hljs_languages:
    - yaml
    - python